[install]
is_configured = 0

[ui]
is_visible = 1
label = Honeyprint Alert

[launcher]
author = Security Team
description = Custom alert action to process honeyprint fingerprints
version = 1.0.0

[package]
check_for_updates = 1
