# ModSecurity audit log
[monitor:///var/log/imprint/modsec_audit.log]
index = imprint
sourcetype = modsec:audit
disabled = false

# ZebraPal command log
[monitor:///var/log/imprint/commands/commands.txt]
index = imprint
sourcetype = imprint:commands
disabled = false

# Failed logins (SpaceY)
[monitor:///var/log/imprint/auth/failed_logins.log]
index = imprint
sourcetype = imprint:auth
disabled = false
